Install pyiron-data
This resolved the missing potential problem. Now `
ImportError: cannot import name 'UnfoldingPrism' from 'pyiron_atomistics.lammps.structure' (/Users/liamhuber/dev/miniforge3/envs/pycor12/lib/python3.12/site-packages/pyiron_atomistics/lammps/structure.py)`