Cecam top-to-bottom (#25)
* Copy cecam and reference data

As a first step to a top-to-bottom up-to-date example

* Copy and finally remove the reference files

So the core reference data stays safely unchanged

* Set up infrastructure for DB

And ensure that the loaded graphs reference the created db

* cecam notebook progress

* cecam notebook progress

Got a full-graph run working (at least in these cases)
Stuck now at running a raw graph node who has been initialized via state

* Re-execute notebook

Resolving https://github.com/JNmpi/pyiron_core/pull/37 squashed the [bug](https://github.com/JNmpi/pyiron_core/issues/32) I introduced, so the cell I was stuck on (pulling a loaded graph) is fine now

* Add missing json file and reexecute

I just missed copying the file on my first pass

* More progress on the notebook

* Ensure tab selection

"Selecting" the already selected tab did nothing, so select a different one first. I guess this gets really annoying if you load a single graph, as then you need to actually open a tab to make a _new_ workflow and go back.

Basically the solution is to just resole https://github.com/JNmpi/pyiron_core/issues/23

* Notebook changes

* More notebook progress

I'm stuck on missing potentials now, which should be soluble

* Install pyiron-data

This resolved the missing potential problem. Now `
ImportError: cannot import name 'UnfoldingPrism' from 'pyiron_atomistics.lammps.structure' (/Users/liamhuber/dev/miniforge3/envs/pycor12/lib/python3.12/site-packages/pyiron_atomistics/lammps/structure.py)`

* Downgrade atomistics

https://github.com/JNmpi/pyiron_core/issues/51

* Add to env

I think my intent was for this to be for the whole project -- the main library and the nodes library both.

* Rename env file

To use the right extension.

* Rerun notebook

* Run top-to-bottom!

* Demo nested macros

* Clean up more thoroughly

* Extend gitignore